# Generated by Django 5.2 on 2025-06-09 22:45

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Proje için bir isim.', max_length=255)),
                ('csv_file_path', models.CharField(help_text='Yüklenen CSV dosyasının sunucudaki yolu.', max_length=500)),
                ('analysis_results', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Veri analizi sonuçları (özet, eksik veri vb.).')),
                ('model_results', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Model eğitim sonuçları (metrikler, özellik önemleri vb.).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Projenin oluşturulduğu zaman.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Projenin en son güncellendiği zaman.')),
                ('user', models.ForeignKey(help_text='Bu projenin sahibi olan kullanıcı.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
