# Generated by Django 5.2.4 on 2025-07-05 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_analysis_delete_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='is_favorite',
            new_name='is_public',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='image',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
