# Generated by Django 5.2.4 on 2025-07-05 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_rename_is_favorite_analysis_is_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_analyses', to=settings.AUTH_USER_MODEL),
        ),
    ]
