# Generated by Django 5.2.4 on 2025-07-06 18:14

import analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=analyzer.models.user_avatar_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_choice',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
