# Generated by Django 5.2.4 on 2025-07-06 22:10

import analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_userprofile_avatar_userprofile_avatar_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=analyzer.models.analysis_cover_path),
        ),
        migrations.AddField(
            model_name='analysis',
            name='cover_plot_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
