# Generated by Django 5.2.4 on 2025-07-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_analysis_cover_image_analysis_cover_plot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='random_cover',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_choice',
            field=models.CharField(default='avatars1.png', max_length=100),
        ),
    ]
